### ISSUE TITLE
Submit port?

### ISSUE THREAD

**Issue by sporkman** [steakknife/ruby-install-freebsd#4]
It's great this is here, but why not submit it as a port?

For those of us that maintain our own packages, this workaround of having to keep reinstalling this port with each ports tree update is a bit wonky.

**Comment by steakknife** [comment]
This repo exists because the FreeBSD Ports team was unresponsive / unapproachable.

Feel free to "be the change you seek," since I don't have the bandwidth to this right now.

https://github.com/freebsd/freebsd-ports

https://bugs.freebsd.org/bugzilla
